{% set name = "redshift_connector" %}
{% set version = "2.0.889" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/amazon-redshift-python-driver/archive/v{{ version }}.tar.gz
  sha256: 4cf8fb076adc5787471b5f4dd81dbe19157cff9ebca11683c1e4c2958239b5a3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - scramp >=1.2.0,<1.5.0
    - pytz >=2020.1,<2021.9
    - beautifulsoup4 >=4.7.0,<5.0.0
    - boto3 >=1.16.8,<2.0.0
    - requests >=2.23.0,<2.26.1
    - lxml >=4.6.2
    - botocore >=1.19.8,<2.0.0
    - packaging

test:
  imports:
    - redshift_connector

about:
  home: https://github.com/aws/amazon-redshift-python-driver/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Pure Python connector for Amazon Redshift
  description: |
    redshift_connector is the Amazon Redshift connector for Python. Easy integration with 
    pandas and numpy, as well as support for numerous Amazon Redshift specific features 
    help you get you the most out of your data.
  doc_url: https://github.com/aws/amazon-redshift-python-driver/
  dev_url: https://github.com/aws/amazon-redshift-python-driver/

extra:
  recipe-maintainers:
    - Brooke-white
